const router = require("express").Router()
const userController = require("../controllers/userController")
router.get("/", userController.getInformation)
router.post("/signIn", userController.signIn)
router.post("/signUp", userController.signUp)
router.post("/signUp/verify", userController.verifyOtp)
router.post("/update", userController.updateInformation)
router.post("/update_user_course", userController.updateUserCourse)
router.get("/:Username", userController.getUserInformation)
module.exports = router